### ISSUE TITLE
Need Software Team Content

### ISSUE THREAD

**Issue by Waidhoferj** [calpoly-csai/csai-docs#5]
Plz write about your team and include a getting stared section.

**Comment by Waidhoferj** [comment]
Page location in repo: `/src/pages/teams/software.mdx`
Check out the [App Dev](https://github.com/calpoly-csai/csai-docs/blob/master/src/pages/teams/app-development.mdx) team page for structural reference.

**Comment by Jason-Ku** [comment]
Will do sometime this weekend

**Comment by Jason-Ku** [comment]
Added some stuff but still need to add more on onboarding and github committing (although that may go outside the software page)

**Comment by Waidhoferj** [comment]
Yeah I think tutorials should be generalized in a separate section and linked to from each team page. I'm still considering which UI structure would make the content most navigable.

**Comment by Waidhoferj** [comment]
Jason covered the basics in #13 and #16
